# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Anonimización aplicada al ámbito médico
author: Guillaume Gelabert
logo: figures/logo-serikat.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "force" # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache: "" # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns: [] # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout: 300 # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp:
      false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
      # otherwise the notebook's parent directory will be the cwd.
  allow_errors: false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output: show # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    latex_engine: xelatex
    targetname: cdti.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/GuiGel/MedDocAn  # Online location of your book
  path_to_book: cdti  # Optional path to your book, relative to the repository root
  branch: cdti  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - deflist

sphinx:
  config:
    bibtex_reference_style: author_year


# sphinx:
#     extra_extensions: # A list of extra extensions to load by Sphinx (added to those already used by JB).
#         - "sphinx.ext.autodoc"
#         - "sphinx.ext.napoleon"
#         - "sphinx.ext.viewcode"
#         - "sphinx.ext.intersphinx"
#         - "autoapi.extension"
#         - "myst_nb"
#         - "sphinx_codeautolink"
#     local_extensions: # A list of local extensions to load by sphinx specified by "name: path" items
#     config: # key-value pairs to directly over-ride the Sphinx configuration
#         add_module_names: false
#         html_js_files:
#             - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
#         bibtex_reference_style: author_year
#         autoapi_dirs:
#             - "../meddocan"
#         autoapi_root: "api"
#         autoapi_add_toctree_entry: false
#         autoapi_keep_files: false
#         autoapi_options:
#             - "members"
#             # - "undoc-members"
#             - "private-members"
#             - "show-inheritance"
#             - "special-members"
#             - "imported-members"
#         # RestructuredText that will be include at the beginning of every source file.
#         # rst_prolog: 
#         #   - """
#         #     .. |Doc| replace:: `Doc <https://spacy.io/api/doc>`__
#         #     .. |Token| replace:: `Token <https://spacy.io/api/token>`__
#         #     .. |Span| replace:: `Span <https://spacy.io/api/span>`__
#         #     .. |spaCy| replace:: `spaCy <https://spacy.io>`__
#         #   """
#         intersphinx_mapping:
#             # url is the place to look for objects.inv file generated by sphinx
#             matplotlib:
#                 - "https://matplotlib.org/stable/"
#                 - null
#             numpy:
#                 - "https://docs.scipy.org/doc/numpy/"
#                 - null
#             pandas:
#                 - "https://pandas.pydata.org/pandas-docs/stable/"
#                 - null
#             python:
#                 - "https://docs.python.org/3"
#                 - null
#             scipy:
#                 - "https://docs.scipy.org/doc/scipy/reference/"
#                 - null
#             seaborn:
#                 - "https://seaborn.pydata.org/"
#                 - null
#             sklearn:
#                 - "https://scikit-learn.org/stable/"
#                 - null